# vim: sw=2:ts=2:et:ft=ruby

SHELLARGS = []
SHELLARGS << (ENV['repoowner'] || '')
SHELLARGS << (ENV['branch'] || '')
SHELLARGS << (ENV['proxy_repo'] || '')

Vagrant.configure("2") do |config|
  config.vm.define "fdi-builder", primary: true do |machine|

    machine.vm.hostname = "fdi-builder-vm"
    machine.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.provider :libvirt do |libvirt|
      libvirt.driver = "kvm"
    end

    config.vm.provider :libvirt do |domain, cfg|
      cfg.vm.box = 'centos/stream9'
      domain.memory = 7990
      domain.cpus = 2
      domain.nested = true
      domain.disk_driver :cache => 'unsafe'
      domain.machine_virtual_size = 40
    end

    machine.vm.provision :shell, :path => 'build_image.sh', :args => SHELLARGS

  end
end
